export type QuoteCategory = 'SERVICE' | 'LEADERSHIP' | 'EXCELLENCE' | 'GRATITUDE' | 'SUKHI';

export type Quote = {
  text: string;
  author?: string;
  category: QuoteCategory;
};

const SERVICE: Quote[] = [
  { text: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou", category: "SERVICE" },
  { text: "Excellence is doing ordinary things extraordinarily well.", category: "SERVICE" },
  { text: "Make each guest feel like the most important person in the room — because in that moment, they are.", category: "SERVICE" },
  { text: "True hospitality consists of giving the best of yourself to your guests.", author: "Eleanor Roosevelt", category: "SERVICE" },
  { text: "The customer's perception is your reality.", author: "Kate Zabriskie", category: "SERVICE" },
  { text: "Service is not a department. It's an attitude.", category: "SERVICE" },
  { text: "When you serve with love, it shows in everything you do.", category: "SERVICE" },
  { text: "Great service turns a meal into a memory.", category: "SERVICE" },
  { text: "Every table is someone's special occasion — even if they haven't told you.", category: "SERVICE" },
  { text: "The secret of success is to treat all customers as if your world revolves around them.", category: "SERVICE" },
  { text: "The details are not the details. They make the design.", author: "Charles Eames", category: "SERVICE" },
  { text: "Quality is never an accident. It is always the result of intelligent effort.", author: "John Ruskin", category: "SERVICE" },
  { text: "To give real service you must add something which cannot be bought or measured with money — sincerity and integrity.", author: "Don Alden Adams", category: "SERVICE" },
  { text: "Customers don't expect you to be perfect. They do expect you to fix things when they go wrong.", author: "Donald Porter", category: "SERVICE" },
  { text: "The goal as a company is to have customer service that is not just the best, but legendary.", author: "Sam Walton", category: "SERVICE" },
  { text: "A satisfied customer is the best business strategy of all.", author: "Michael LeBoeuf", category: "SERVICE" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin", category: "SERVICE" },
  { text: "Hospitality is almost impossible to teach. It's a way of life that has to come from within.", author: "Danny Meyer", category: "SERVICE" },
  { text: "In hospitality the smile is the most important ingredient.", category: "SERVICE" },
  { text: "Service means giving more than is expected and asking for nothing in return.", category: "SERVICE" },
  { text: "Every guest who walks through the door is a gift.", category: "SERVICE" },
  { text: "The best restaurants don't just feed people — they restore them.", category: "SERVICE" },
  { text: "Great hospitality makes strangers feel like family.", category: "SERVICE" },
  { text: "You can't fake caring. Guests feel it immediately.", category: "SERVICE" },
  { text: "The table you serve tonight might be someone's first date, anniversary or last meal together — give it everything.", category: "SERVICE" },
  { text: "Presence is the greatest gift you can offer a guest.", category: "SERVICE" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", category: "SERVICE" },
  { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali", category: "SERVICE" },
  { text: "Life's most persistent and urgent question is: what are you doing for others?", author: "Martin Luther King Jr.", category: "SERVICE" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson", category: "SERVICE" },
  { text: "We make a living by what we get. We make a life by what we give.", author: "Winston Churchill", category: "SERVICE" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", category: "SERVICE" },
  { text: "In a world where you can be anything, be kind.", category: "SERVICE" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain", category: "SERVICE" },
  { text: "The simple act of caring is heroic.", author: "Edward Albert", category: "SERVICE" },
  { text: "Service with a smile isn't just good manners — it's good medicine.", category: "SERVICE" },
  { text: "The most important thing is to try and inspire people so that they can be great at whatever they want to do.", author: "Kobe Bryant", category: "SERVICE" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", category: "SERVICE" },
  { text: "The more you engage with customers the clearer things become and the easier it is to determine what you should be doing.", author: "John Russell", category: "SERVICE" },
  { text: "There is only one corner of the universe you can be certain of improving and that is your own self.", author: "Aldous Huxley", category: "SERVICE" },
];

const LEADERSHIP: Quote[] = [
  { text: "A leader's job is not to do the work for others, it's to help others figure out how to do it themselves.", author: "Simon Sinek", category: "LEADERSHIP" },
  { text: "The strength of the team is each individual member. The strength of each member is the team.", author: "Phil Jackson", category: "LEADERSHIP" },
  { text: "Leadership is not about being in charge. It's about taking care of those in your charge.", author: "Simon Sinek", category: "LEADERSHIP" },
  { text: "Culture eats strategy for breakfast.", author: "Peter Drucker", category: "LEADERSHIP" },
  { text: "A good leader takes a little more than their share of the blame, a little less than their share of the credit.", author: "Arnold Glasgow", category: "LEADERSHIP" },
  { text: "The best managers don't manage people. They inspire them.", category: "LEADERSHIP" },
  { text: "Your team will rise to the level of culture you create.", category: "LEADERSHIP" },
  { text: "Treat your staff the way you want them to treat your best customers.", author: "Stephen Covey", category: "LEADERSHIP" },
  { text: "A great team makes the impossible feel inevitable.", category: "LEADERSHIP" },
  { text: "When your team wins, celebrate loudly. When they struggle, support quietly.", category: "LEADERSHIP" },
  { text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "LEADERSHIP" },
  { text: "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.", author: "Jack Welch", category: "LEADERSHIP" },
  { text: "Management is doing things right. Leadership is doing the right things.", author: "Peter Drucker", category: "LEADERSHIP" },
  { text: "The most powerful leadership tool you have is your own personal example.", author: "John Wooden", category: "LEADERSHIP" },
  { text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John Maxwell", category: "LEADERSHIP" },
  { text: "Outstanding leaders go out of their way to boost the self-esteem of their personnel.", author: "Sam Walton", category: "LEADERSHIP" },
  { text: "The art of communication is the language of leadership.", author: "James Humes", category: "LEADERSHIP" },
  { text: "People don't buy what you do, they buy why you do it.", author: "Simon Sinek", category: "LEADERSHIP" },
  { text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", author: "John Quincy Adams", category: "LEADERSHIP" },
  { text: "A good coach can change a game. A great coach can change a life.", author: "John Wooden", category: "LEADERSHIP" },
  { text: "You manage things. You lead people.", author: "Grace Hopper", category: "LEADERSHIP" },
  { text: "Great leaders don't tell you what to do. They show you how it's done.", category: "LEADERSHIP" },
  { text: "The best gift a manager can give their team is clarity, trust and recognition.", category: "LEADERSHIP" },
  { text: "Earn your team's respect every single day — it's never guaranteed.", category: "LEADERSHIP" },
  { text: "A restaurant is only as good as its worst day — lead to make every day the best.", category: "LEADERSHIP" },
  { text: "Your team watches everything you do. Lead like it.", category: "LEADERSHIP" },
  { text: "Create a culture where people are excited to come to work.", category: "LEADERSHIP" },
  { text: "Recognise effort loudly. Correct mistakes quietly.", category: "LEADERSHIP" },
  { text: "The kitchen and the floor are one team. Great managers make sure everyone knows it.", category: "LEADERSHIP" },
  { text: "Your energy as a leader sets the temperature for the entire room.", category: "LEADERSHIP" },
  { text: "Example is not the main thing in influencing others. It is the only thing.", author: "Albert Schweitzer", category: "LEADERSHIP" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "LEADERSHIP" },
  { text: "Do not follow where the path may lead. Go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "LEADERSHIP" },
  { text: "The greatest leader is not necessarily the one who does the greatest things. They are the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "LEADERSHIP" },
  { text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "LEADERSHIP" },
  { text: "Great leaders are almost always great simplifiers.", author: "Colin Powell", category: "LEADERSHIP" },
  { text: "The task of leadership is not to put greatness into people, but to elicit it, for the greatness is there already.", author: "John Buchan", category: "LEADERSHIP" },
  { text: "A good manager is someone who isn't worried about their own career but rather the careers of those who work for them.", author: "H.S.M. Burns", category: "LEADERSHIP" },
  { text: "A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go, but ought to be.", author: "Rosalynn Carter", category: "LEADERSHIP" },
  { text: "People don't care how much you know until they know how much you care.", author: "Theodore Roosevelt", category: "LEADERSHIP" },
];

const EXCELLENCE: Quote[] = [
  { text: "We are what we repeatedly do. Excellence then is not an act but a habit.", author: "Aristotle", category: "EXCELLENCE" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "EXCELLENCE" },
  { text: "Show up, work hard, be kind, and amazing things will happen.", category: "EXCELLENCE" },
  { text: "Small things done with great love change the world.", author: "Mother Teresa", category: "EXCELLENCE" },
  { text: "Champions aren't made in gyms. They're made from something deep inside them.", author: "Muhammad Ali", category: "EXCELLENCE" },
  { text: "Do what you do so well that they will want to see it again and bring their friends.", author: "Walt Disney", category: "EXCELLENCE" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke", category: "EXCELLENCE" },
  { text: "Today is a new opportunity to show what you're made of.", category: "EXCELLENCE" },
  { text: "The difference between ordinary and extraordinary is that little extra.", category: "EXCELLENCE" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", category: "EXCELLENCE" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "EXCELLENCE" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "EXCELLENCE" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi", category: "EXCELLENCE" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "EXCELLENCE" },
  { text: "Success is no accident. It is hard work, perseverance, learning, sacrifice and most of all love of what you are doing.", author: "Pelé", category: "EXCELLENCE" },
  { text: "I've missed more than 9,000 shots in my career. I've lost almost 300 games. I've failed over and over and that's why I succeed.", author: "Michael Jordan", category: "EXCELLENCE" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "EXCELLENCE" },
  { text: "The more I practice the luckier I get.", author: "Gary Player", category: "EXCELLENCE" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi", category: "EXCELLENCE" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice", category: "EXCELLENCE" },
  { text: "It's not about the hours you put in — it's about what you put into the hours.", category: "EXCELLENCE" },
  { text: "Discipline is choosing between what you want now and what you want most.", category: "EXCELLENCE" },
  { text: "Push yourself because no one else is going to do it for you.", category: "EXCELLENCE" },
  { text: "Dream big. Work hard. Stay focused.", category: "EXCELLENCE" },
  { text: "Every shift is a chance to be better than yesterday.", category: "EXCELLENCE" },
  { text: "Show up fully or don't show up at all.", category: "EXCELLENCE" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr.", category: "EXCELLENCE" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier", category: "EXCELLENCE" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "EXCELLENCE" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "EXCELLENCE" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "EXCELLENCE" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "EXCELLENCE" },
  { text: "Don't watch the clock. Do what it does — keep going.", author: "Sam Levenson", category: "EXCELLENCE" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn", category: "EXCELLENCE" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "EXCELLENCE" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston", category: "EXCELLENCE" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "EXCELLENCE" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong", category: "EXCELLENCE" },
  { text: "Consistency is the hallmark of the unexceptional — be exceptional every single time.", category: "EXCELLENCE" },
  { text: "The best preparation for tomorrow is doing your best today.", category: "EXCELLENCE" },
];

const GRATITUDE: Quote[] = [
  { text: "Gratitude turns what we have into enough.", category: "GRATITUDE" },
  { text: "Your attitude is contagious — make sure it's worth catching.", category: "GRATITUDE" },
  { text: "Start each shift grateful for the opportunity to make someone's day better.", category: "GRATITUDE" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama", category: "GRATITUDE" },
  { text: "When you change the way you look at things, the things you look at change.", author: "Dr. Wayne Dyer", category: "GRATITUDE" },
  { text: "Gratitude is the healthiest of all human emotions.", author: "Zig Ziglar", category: "GRATITUDE" },
  { text: "A positive attitude causes a chain reaction of positive thoughts and outcomes.", category: "GRATITUDE" },
  { text: "Joy is what happens when we allow ourselves to recognize how good things really are.", author: "Marianne Williamson", category: "GRATITUDE" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", category: "GRATITUDE" },
  { text: "Wake up with purpose. Show up with passion.", category: "GRATITUDE" },
  { text: "Enough is a feast.", author: "Buddhist proverb", category: "GRATITUDE" },
  { text: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", author: "Melody Beattie", category: "GRATITUDE" },
  { text: "The root of joy is gratefulness.", author: "David Steindl-Rast", category: "GRATITUDE" },
  { text: "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.", author: "Voltaire", category: "GRATITUDE" },
  { text: "We often take for granted the very things that most deserve our gratitude.", author: "Cynthia Ozick", category: "GRATITUDE" },
  { text: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author: "William Arthur Ward", category: "GRATITUDE" },
  { text: "Gratitude is the fairest blossom which springs from the soul.", author: "Henry Ward Beecher", category: "GRATITUDE" },
  { text: "The thankful receiver bears a plentiful harvest.", author: "William Blake", category: "GRATITUDE" },
  { text: "Enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault", category: "GRATITUDE" },
  { text: "Joy is not in things. It is in us.", author: "Richard Wagner", category: "GRATITUDE" },
  { text: "Count your blessings, not your problems.", category: "GRATITUDE" },
  { text: "Today is a gift — that's why it's called the present.", category: "GRATITUDE" },
  { text: "A grateful heart is a magnet for miracles.", category: "GRATITUDE" },
  { text: "Be thankful for what you have and you'll end up having more.", author: "Oprah Winfrey", category: "GRATITUDE" },
  { text: "The happiest people don't have the best of everything — they make the best of everything.", category: "GRATITUDE" },
  { text: "This shift is an opportunity. Treat it like one.", category: "GRATITUDE" },
  { text: "Someone out there would love to have your job today.", category: "GRATITUDE" },
  { text: "Find something beautiful in every shift.", category: "GRATITUDE" },
  { text: "Gratitude turns a job into a calling.", category: "GRATITUDE" },
  { text: "Begin each shift with a grateful heart and watch everything change.", category: "GRATITUDE" },
  { text: "When I started counting my blessings, my whole life turned around.", author: "Willie Nelson", category: "GRATITUDE" },
  { text: "Gratitude is not only the greatest of virtues, but the parent of all others.", author: "Cicero", category: "GRATITUDE" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh", category: "GRATITUDE" },
  { text: "Walk as if you are kissing the earth with your feet.", author: "Thich Nhat Hanh", category: "GRATITUDE" },
  { text: "In ordinary life we hardly realize that we receive a great deal more than we give.", author: "Dietrich Bonhoeffer", category: "GRATITUDE" },
  { text: "Acknowledging the good that you already have in your life is the foundation for all abundance.", author: "Eckhart Tolle", category: "GRATITUDE" },
  { text: "Let us be grateful to the people who make us happy.", author: "Marcel Proust", category: "GRATITUDE" },
  { text: "Piglet noticed that even though he had a very small heart, it could hold a rather large amount of gratitude.", author: "A.A. Milne", category: "GRATITUDE" },
  { text: "The way to happiness is to count your blessings while others are adding up their troubles.", category: "GRATITUDE" },
  { text: "At the end of the day, let there be no excuses, no explanations, no regrets.", author: "Steve Maraboli", category: "GRATITUDE" },
];

const SUKHI: Quote[] = [
  { text: "Your nervous system is your greatest asset. Regulate it before every shift.", category: "SUKHI" },
  { text: "Service is healing. Every interaction is an opportunity to elevate someone's day.", category: "SUKHI" },
  { text: "The energy you bring to the table is as important as the food on it.", category: "SUKHI" },
  { text: "Coherence is the key — when you're aligned inside, your service shines outside.", category: "SUKHI" },
  { text: "Symptoms are signals. A difficult customer is an invitation to grow.", category: "SUKHI" },
  { text: "Your body is intelligent. Trust it, nourish it, and it will show up for you.", category: "SUKHI" },
  { text: "Healing begins with awareness. Great service begins the same way.", category: "SUKHI" },
  { text: "Every shift is a chance to practice being fully present.", category: "SUKHI" },
  { text: "The greatest tip you can give someone is your full attention.", category: "SUKHI" },
  { text: "Show up as the best version of yourself — your team and your guests deserve it.", category: "SUKHI" },
  { text: "Your energy is contagious. Make sure it heals, not harms.", category: "SUKHI" },
  { text: "The nervous system doesn't lie. If you feel off, pause, breathe, reset.", category: "SUKHI" },
  { text: "Presence is power. Be here fully.", category: "SUKHI" },
  { text: "You cannot pour from an empty cup. Take care of yourself so you can care for others.", category: "SUKHI" },
  { text: "The body keeps score. Honour yours before every shift.", category: "SUKHI" },
  { text: "Stress is a signal, not a sentence. Listen to it.", category: "SUKHI" },
  { text: "When you regulate yourself, you regulate the room.", category: "SUKHI" },
  { text: "Biology is destiny only if you ignore it. Master your physiology and you master your performance.", category: "SUKHI" },
  { text: "A regulated nervous system is the foundation of extraordinary service.", category: "SUKHI" },
  { text: "Your breath is your reset button. Use it.", category: "SUKHI" },
  { text: "You are not your worst shift. You are your commitment to showing up again.", category: "SUKHI" },
  { text: "Healing is not linear. Neither is growth. Keep going.", category: "SUKHI" },
  { text: "The greatest service you can offer is your full, undivided presence.", category: "SUKHI" },
  { text: "Coherence between mind, body and action — that's where peak performance lives.", category: "SUKHI" },
  { text: "Every interaction is either draining or healing. Choose to heal.", category: "SUKHI" },
  { text: "The quality of your attention determines the quality of the experience you create.", category: "SUKHI" },
  { text: "Rest is not laziness. It's preparation for excellence.", category: "SUKHI" },
  { text: "You were made for this. Show up like you believe it.", category: "SUKHI" },
  { text: "Small acts of genuine kindness create ripples that last long after the shift ends.", category: "SUKHI" },
  { text: "Today, be the reason someone felt seen, heard and valued.", category: "SUKHI" },
  { text: "Your cells are listening to every thought you think. Think well.", category: "SUKHI" },
  { text: "The shift starts before you arrive. Prepare your mind, prepare your body.", category: "SUKHI" },
  { text: "Nervous system regulation is not a luxury — it's your highest performance tool.", category: "SUKHI" },
  { text: "You are a biological miracle showing up to serve. Never forget that.", category: "SUKHI" },
  { text: "Between stimulus and response there is a space. In that space lies your power.", category: "SUKHI" },
  { text: "The body is not a machine. It is an intelligent, self-healing system. Honour it.", category: "SUKHI" },
  { text: "When you breathe consciously you take back control of your state.", category: "SUKHI" },
  { text: "Your posture is your power. Stand tall before every shift.", category: "SUKHI" },
  { text: "Connection heals. Every genuine interaction you have tonight matters more than you know.", category: "SUKHI" },
  { text: "The greatest gift you can give your guests tonight is a regulated, present, joyful you.", category: "SUKHI" },
];

import AsyncStorage from '@react-native-async-storage/async-storage';

const STAFF_POOL: Quote[] = [...SERVICE, ...GRATITUDE, ...SUKHI];
const MANAGER_POOL: Quote[] = [...LEADERSHIP, ...EXCELLENCE];

const QUOTE_COUNTER_KEY = 'mise_quote_counter';

export async function getDailyQuote(role: 'manager' | 'staff'): Promise<Quote> {
  const pool = role === 'manager' ? MANAGER_POOL : STAFF_POOL;

  const stored = await AsyncStorage.getItem(QUOTE_COUNTER_KEY);
  const counter = stored !== null ? parseInt(stored, 10) : 0;

  await AsyncStorage.setItem(QUOTE_COUNTER_KEY, String(counter + 1));

  return pool[counter % pool.length];
}
